/******************************************************************************/
/*            Generated by IBExpert 2016.4.4.1 26/07/2016 17:39:50            */
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES NONE;

CONNECT 'D:\projetos\SisEvolFisio\DADOS.FDB' USER 'SYSDBA' PASSWORD 'masterkey';



/******************************************************************************/
/*                                  Domains                                   */
/******************************************************************************/

CREATE DOMAIN D_ANO AS
SMALLINT;

CREATE DOMAIN D_DESCRICAO AS
VARCHAR(150) CHARACTER SET WIN1252
COLLATE WIN_PTBR;

CREATE DOMAIN D_FK AS
BIGINT;

CREATE DOMAIN D_ID AS
BIGINT
DEFAULT '0'
NOT NULL;



/******************************************************************************/
/*                                 Generators                                 */
/******************************************************************************/

CREATE GENERATOR GEN_PACIENTES START WITH 0 INCREMENT BY 1;
SET GENERATOR GEN_PACIENTES TO 30;



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/



CREATE TABLE EVOLUCAO (
    ID_EVOLUCAO    D_ID GENERATED BY DEFAULT AS IDENTITY,
    DATA_EVOLUCAO  DATE NOT NULL,
    EVOLUCAO       BLOB SUB_TYPE 1 SEGMENT SIZE 1024 NOT NULL,
    FK_PACIENTE    D_FK
);

CREATE TABLE PACIENTES (
    ID_PACIENTE    D_ID GENERATED BY DEFAULT AS IDENTITY,
    CODIGO         D_ID GENERATED BY DEFAULT AS IDENTITY,
    NOME           D_DESCRICAO NOT NULL,
    NASCIMENTO     DATE,
    ENDERECO       D_DESCRICAO,
    DIAG_CLINICO   BLOB SUB_TYPE 1 SEGMENT SIZE 256,
    AVAL_FISIO     BLOB SUB_TYPE 1 SEGMENT SIZE 256,
    DIAG_FISIO     BLOB SUB_TYPE 1 SEGMENT SIZE 256,
    OBJETIVO       BLOB SUB_TYPE 1 SEGMENT SIZE 256,
    CONDUTA_FISIO  BLOB SUB_TYPE 1 SEGMENT SIZE 256
);



/******************************************************************************/
/*                          Autoincrement generators                          */
/******************************************************************************/

ALTER TABLE EVOLUCAO ALTER ID_EVOLUCAO RESTART WITH 6;
ALTER TABLE PACIENTES ALTER ID_PACIENTE RESTART WITH 7;
ALTER TABLE PACIENTES ALTER CODIGO RESTART WITH 8;




/******************************************************************************/
/*                                Primary keys                                */
/******************************************************************************/

ALTER TABLE EVOLUCAO ADD CONSTRAINT PK_EVOLUCAO PRIMARY KEY (ID_EVOLUCAO);
ALTER TABLE PACIENTES ADD CONSTRAINT PK_PACIENTES PRIMARY KEY (ID_PACIENTE);


/******************************************************************************/
/*                                Foreign keys                                */
/******************************************************************************/

ALTER TABLE EVOLUCAO ADD CONSTRAINT FK_EVOLUCAO_1 FOREIGN KEY (FK_PACIENTE) REFERENCES PACIENTES (ID_PACIENTE);


/******************************************************************************/
/*                                  Triggers                                  */
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/*                            Triggers for tables                             */
/******************************************************************************/



/* Trigger: TR_PACIENTES_INC_ID */
CREATE OR ALTER TRIGGER TR_PACIENTES_INC_ID FOR PACIENTES
ACTIVE BEFORE INSERT POSITION 0
AS
begin
  --criado para o delphi/firedac reconhecer o campo como autoinc
  if (new.id_paciente is null) then
    new.id_paciente = gen_id(gen_pacientes,1);
end
^
SET TERM ; ^



/******************************************************************************/
/*                               DDL privileges                               */
/******************************************************************************/

